site_name: CoPilot Metadata
site_url: https://github.com/dmccrearytg/copilot-metadata
site_description: 'Resources for teaching classes on Micro Simulators using generative AI and ChatGPT.'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccrearytg.github.io/copilot-metadata'
repo_url: 'https://github.com/dmccrearytg/copilot-metadata'
edit_uri: edit/master/docs/

nav:
  - Home: index.md
  - About: about.md
  - Getting Started: getting-started.md
  - Concepts:
    - Introduction: concepts/index.md
    - Metadata Architecture: concepts/architecture.md
    - Metadata JSON File: concepts/json-file-format.md
    - Metadata Transformers: concepts/metadata-transformers.md
    - Metadata Loaders: concepts/metadata-loaders.md
  - Generating Personas: generating-personas.md
  - Generating Questions: generating-questions.md
  - Sample Personas: sample-personas.md
  - Solution Kit Metadata: solution-kit-metadata.md
  - Solution Kit Questions:
    - Introduction: questions/index.md
    - Transaction Fraud: questions/transaction-fraud.md
    - Credit Card Application Fraud: questions/credit-card-application-fraud.md
    - Connected Customer ER: questions/connected-customer-er.md
    - Know Your Customer: questions/know-your-customer-er.md
    - Fraudster Detection: questions/fraudster-detection.md
    - Mule Account Detection: questions/mule-account-detection.md
    - Financial Customer 360: questions/financial-c360.md
    - Investment Product Recommendations: questions/investment-product-recommendations.md
    - Merchant Product Recommendations: questions/merchant-product-recommendations.md
    - Suppy Chain Management: questions/supply-chain-management.md
    - Anti-Money Laundering: questions/anti-money-laundering.md
    - Inventory Management: questions/inventory-management.md
    - Network Digital Twin Knowledge Graph: questions/network-digital-twin-knolwedge-graph.md
  - Document Data Model: document-data-model.md
  - Glossary: glossary.md
  - Contact: contact.md

# edit_uri: 'blob/master/docs'
theme:
  name: material
  logo: img/tg-logo-small.png
  favicon: img/favicon.ico
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
plugins:
  - search
#  - social
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      linenums: true
# extra:
#  analytics:
#    provider: google
#    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
#    property: G-BBR7MPK96Z