name: Extract Personas

on:
  push:
    paths:
      - 'solution-kit-metadata.json'

jobs:
  extract_personas:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run extract-personas script
      run: |
        python extract-personas.py solution-kit-metadata.json personas.json

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add personas.json
        git commit -m 'Update personas.json'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
